---
title: InteractiveFiction
timezone: America/New_York
collections:
  characters:
    title: Characters
    output: true
  memories:
    title: Memories
    output: true
    permalink: "/:collection/:title/index.html"
  posts:
    title: Posts
    output: true
  TestingGround:
    title: Testing Ground
    output: true
    permalink: "/:collection/:title/index.html"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: memories
    type: pages
  values:
    perspective: The Butcher
    world-date: 2019-07-13 17:55:00.000000000 Z
    characters: []
    location: 
    MemoryId: nospaces
    Memory Label: short display name
    MemoryCombo: []
    Image: 
    layout: memory
kramdown:
  input: GFM
  hard_wrap: false
plugins:
- jekyll-coffeescript
- jekyll-paginate
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
permalink: pretty
sass:
  sass_dir: css
baseurl: 
